name: Deploy Email Verifier Backend to DigitalOcean

on:
  push:
    branches: [ main ]
    paths:
      - 'astromail-email-verifier/**'
  workflow_dispatch:

env:
  NODE_ENV: production
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        working-directory: ./astromail-email-verifier
        run: npm ci

      - name: Build NestJS app
        working-directory: ./astromail-email-verifier
        run: npm run build
        env:
          NODE_ENV: production

      - name: Install PM2 globally on local machine
        run: npm install -g pm2

      - name: Generate deployment package
        run: |
          mkdir -p deploy-package
          cp -r astromail-email-verifier/dist deploy-package/
          cp -r astromail-email-verifier/node_modules deploy-package/
          cp astromail-email-verifier/package.json deploy-package/
          cp astromail-email-verifier/package-lock.json deploy-package/
          [ -f "astromail-email-verifier/nest-cli.json" ] && cp astromail-email-verifier/nest-cli.json deploy-package/ || true
          [ -f "astromail-email-verifier/.env.production" ] && cp astromail-email-verifier/.env.production deploy-package/ || true

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "deploy-package/"
          target: "/var/www/astromail-email-verifier"
          strip_components: 1

      - name: Execute remote deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/astromail-email-verifier
            pm2 delete astromail-email-verifier || true
            NODE_ENV=production pm2 start dist/main.js --name "astromail-email-verifier"
            pm2 save